# Generated by Django 4.2.5 on 2023-09-29 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='sport',
        ),
        migrations.AddField(
            model_name='bet',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bet',
            name='date_of_match',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bet',
            name='type_of_bet',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='id_on_api',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='result',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
